name: build

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write # needed to write releases
  id-token: write # needed for keyless signing
  packages: write # needed for ghcr access

jobs:
  staging:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Restore Go cache
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18.x
      - name: Setup CUE
        uses: cue-lang/setup-cue@main
      - name: Vet the CUE definitions
        run: make vet
      - name: Generate deploy manifests
        run: make build
      - name: Build Flux CLI
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        run: |
          git clone https://github.com/fluxcd/flux2.git
          cd flux2 
          git checkout oci
          make build
          ./bin/flux -v
          mv ./bin/flux /usr/local/bin/flux
          cd ..
          rm -rf flux2
      - name: Login to GitHub Container Registry
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: github
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push artifact to staging
        if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
        run: make push
